---
- name: Install Docker
  import_tasks: docker.yml

- name: Install Mastodon & Configure
  import_tasks: mastodon.yml

- name: Install Nginx & Configure
  import_tasks: nginx.yml

- name: Install Postfix & Configure
  import_tasks: postfix.yml
