---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Create nginx site configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ _domain }}"
    mode: '0644'
  notify: Restart nginx

- name: Enable Vault nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ _domain }}"
    dest: "/etc/nginx/sites-enabled/{{ _domain }}"
    state: link
  notify: Restart nginx

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Enable and start nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true

- name: Install logrotate config for Vault audit log
  ansible.builtin.template:
    src: vault-logrotate.j2
    dest: /etc/logrotate.d/vault
    owner: root
    group: root
    mode: '0644'

- name: Setting up SSL certificate
  ansible.builtin.import_role:
    name: certbot_ssl
  vars:
    webserver_stack: lemp
