---
- name: Setting up environment
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  vars_files: [group_vars/linode/vars]
  tasks:
    - name: Generating sudo user and password
      import_tasks: ../linode_helpers/roles/sudouser/tasks/main.yml

    - name: Generating MariaDB root password
      import_tasks: ../linode_helpers/roles/securemysql/tasks/passgen.yml

    - name: Generating Joomla DB and admin passwords
      lineinfile:
        insertafter: EOF
        path: group_vars/linode/vars
        line: |
          joomla_db_password: {{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}
          joomla_admin_password: {{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}
          webserver_stack: lamp
