---
- name: Install Docker latest
  import_role:
    name: docker

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: true

- name: Update Docker daemon to support concurrent downloads
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "max-concurrent-downloads": 10
      }

- name: Restart Docker service
  systemd_service:
    name: docker
    state: restarted
    enabled: true
