---
- name: Write credentials file for sudo user
  ansible.builtin.template:
    src: credentials.j2
    dest: "/home/{{ sudo_username }}/.credentials"
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    mode: '0600'
