---
- name: Install Docker latest
  import_role:
    name: docker

# Appwrite Installer
- name: Ensure Appwrite directory exists
  file:
    path: /opt/appwrite
    state: directory
    mode: '0755'

- name: Run Appwrite installer container
  community.docker.docker_container:
    name: appwrite-installer
    image: appwrite/appwrite:1.9.0
    state: started
    auto_remove: true
    interactive: true
    tty: true
    entrypoint: install
    published_ports:
      - "20080:20080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/appwrite:/usr/src/code/appwrite:rw"

- name: Wait for Appwrite installer to be ready
  wait_for:
    host: localhost
    port: 20080
    delay: 5
    timeout: 120
    state: started
