---
- name: Fetching the latest Memgraph version
  uri:
    url: https://api.github.com/repos/memgraph/memgraph/releases/latest
    return_content: true
    status_code: 200
    body_format: json
  register: release_tag

- name: Setting the latest Memgraph version
  set_fact:
    memgraph_version: "{{ release_tag.json.tag_name[1:] }}"

- name: Installing Memgraph
  apt:
    deb: "https://download.memgraph.com/memgraph/v{{ memgraph_version }}/x86_64-deb/memgraph_{{ memgraph_version }}-1_amd64.deb"

- name: Stopping Memgraph service
  systemd_service:
    name: memgraph
    state: stopped
