---
# valkey
- name: Install depends and create system reqs
  import_tasks: valkey_setup.yml

- name: Generate SSL certs
  import_tasks: valkey_ssl.yml

- name: Build valkey
  import_tasks: valkey_build.yml
