---
- name: Install dependencies
  apt:
    pkg: [libssl-dev, libsystemd-dev]

- name: Add disable THP
  copy:
    src: 'files/disable-thp.service'
    dest: '/etc/systemd/system/disable-thp.service'
    mode: '0644'

- name: Start disable THP
  systemd:
    name: disable-thp.service
    state: started
    enabled: true
    daemon-reload: true

- name: Set vm.overcommit
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present

- name: Create valkey group
  group:
    name: valkey
    state: present
    system: true

- name: Create valkey user
  user:
    name: valkey
    group: valkey
    home: '{{ valkey_home_directory }}'
    shell: /sbin/nologin
    expires: -1
    create_home: true
    system: true
    state: present

- name: Create valkey directories
  file:
    path: '{{ item }}'
    state: directory
    owner: valkey
    group: valkey
    mode: '0750'
  loop:
    - '{{ valkey_conf_directory }}'
    - '{{ valkey_data_directory }}'
    - '{{ valkey_install_directory }}'
    - '{{ valkey_ssl_directory }}'
    - '{{ valkey_ssl_ca_directory }}'
    - '{{ valkey_ssl_reqs_directory }}'
    - '{{ valkey_ssl_keys_directory }}'
    - '{{ valkey_ssl_certs_directory }}'
