---
# build valkey
- name: Download valkey archive
  get_url:
    url: 'https://github.com/valkey-io/valkey/archive/refs/tags/{{ valkey_version }}.tar.gz'
    dest: '/tmp/valkey-{{ valkey_version }}.tar.gz'
    mode: '0644'

- name: Unarchive valkey tar.gz
  unarchive:
    src: '/tmp/valkey-{{ valkey_version }}.tar.gz'
    dest: '{{ valkey_install_directory }}'
    extra_opts: [--strip-components=1]

- name: Move the service file
  copy:
    src: 'files/valkey.service'
    dest: '/etc/systemd/system/valkey.service'
    mode: '0644'

- name: Copy config file
  template:
    src: 'templates/valkey.conf.j2'
    dest: '{{ valkey_conf_directory }}/valkey.conf'
    owner: valkey
    group: valkey
    mode: '0644'

- name: Add basic ACL
  template:
    src: 'templates/users.acl.j2'
    dest: '{{ valkey_conf_directory }}/users.acl'
    owner: valkey
    group: valkey
    mode: '0644'

- name: Make valkey
  community.general.make:
    chdir: '{{ valkey_install_directory }}'
    target: install
    params:
      BUILD_TLS: "yes"
      USE_SYSTEMD: "yes"

- name: Start valkey
  systemd:
    name: valkey.service
    state: started
    enabled: true
    daemon-reload: true
