---
- name: Configure SSH UFW rule
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

# only allow dashboard access when client IPs are provided and they want dash public
- name: Configure HTTPs UFW rule
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: ["80", "443"]

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
