---
# Default vars

# Container image versions
langflow_version: "latest"
postgres_version: "16"

# Install directory
langflow_base_dir: "/opt/langflow"

# Langflow port
langflow_port: 7860

# Docker network
langflow_network_name: "langflow_net"
