---
- name: Install CrewAI
  pip:
    name: crewai
    virtualenv: "{{ ansible_env.HOME }}/.env"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
    state: present

- name: Update local PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.env/bin:$PATH"'
    insertafter: EOF
    state: present
