---
# install for root
- name: Install CrewAI for root
  pip:
    name: crewai
    virtualenv: "{{ ansible_env.HOME }}/.env"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
    state: present

#- name: Update local PATH
#  lineinfile:
#    path: "{{ ansible_env.HOME }}/.bashrc"
#    line: 'export PATH="$HOME/.env/bin:$PATH"'
#    insertafter: EOF
#    state: present

# install for sudo user

- name: Install CrewAI for sudo user
  pip:
    name: crewai
    virtualenv: "/home/{{ username }}/.env"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
    state: present
  become: true
  become_user: "{{ username }}"

- name: Update local PATH
  lineinfile:
    path: "{{ item }}/.bashrc"
    line: 'export PATH="$HOME/.env/bin:$PATH"'
    insertafter: EOF
    state: present
  loop:
    - "/root"
    - "/home/{{ username }}"
