---
- name: Environment setup
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  vars_files: [group_vars/linode/vars]
  roles:
    - common
    - jmeter
    - k6
    - siege
    - apache_benchmark
    - post
