---
- name: Install requested add-ons
  import_role:
    name: addons
  when: add_ons != ['none']

- name: Copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd
    mode: '0600'
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Write credentials to file
  copy:
    dest: '/home/{{ username }}/.credentials'
    mode: '0600'
    owner: '{{ username }}'
    group: '{{ username }}'
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}

      Easypanel Admin Email: {{ soa_email_address }}
      Easypanel Admin Password: {{ easypanel_admin_password }}
