---
- name: Install prereqs
  apt:
    name: [expect, sqlite3]
    state: present

- name: Create docker volume
  docker_volume:
    name: "uptime-kuma"

- name: Run uptimekuma docker container
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart_policy: always
    state: started
    volumes: ["uptime-kuma:/app/data"]
    ports: ["127.0.0.1:3001:3001"]

- name: Check for uptime kuma to be ready on localhost
  uri:
    url: "http://127.0.0.1:3001/dashboard"
    method: GET
    return_content: true
  register: result
  until: result.content is search("Uptime Kuma")
  retries: 10
  delay: 5
  failed_when: result.status != 200

# uptime-kuma user creation
- name: Insert uptime kuma user into db
  command:
    cmd: >
      docker exec uptime-kuma sqlite3 data/kuma.db
      "INSERT INTO user (id, username, password, active, timezone, twofa_secret, twofa_status, twofa_last_token)
      VALUES (1, '{{ kuma_user_name }}', NULL, 1, NULL, NULL, 0, NULL);"

- name: Reset uptime kuma user password
  expect:
    command: "docker exec -it uptime-kuma npm run reset-password"
    responses:
      'New Password': '{{ kuma_password }}'
      'Confirm New Password': '{{ kuma_password }}'
    timeout: 30
  no_log: true

- name: Restart the docker container
  docker_container:
    name: uptime-kuma
    restart: true

# Nginx
- name: Install nginx
  apt:
    pkg: [nginx]
    state: present

- name: Config file setup
  template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ _domain }}"
    mode: '0644'

- name: Create a symbolic link for the nginx configuration
  file:
    src: "/etc/nginx/sites-available/{{ _domain }}"
    dest: "/etc/nginx/sites-enabled/{{ _domain }}"
    state: link

- name: Unlink the default nginx configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload nginx service

# ssl_certbot
- name: Setting up ssl certificate
  import_role:
    name: certbot_ssl
