---
- name: Obtain a Let's Encrypt certificate
  import_role:
    name: certbot_ssl
  vars:
    webserver_stack: webroot
    certbot_webroot: "{{ ols_docroot }}"

- name: Install the certbot deploy hook
  copy:
    content: |
      #!/bin/sh
      systemctl restart {{ ols_service }}
    dest: /etc/letsencrypt/renewal-hooks/deploy/restart-lshttpd.sh
    mode: '0755'

- name: Add the TLS listener
  blockinfile:
    path: "{{ ols_httpd_conf }}"
    marker: "# {mark} OPENLITESPEED NODEJS TLS LISTENER"
    block: |
      listener SSL{
        address                  *:443
        secure                   1
        keyFile                  /etc/letsencrypt/live/{{ _domain }}/privkey.pem
        certFile                 /etc/letsencrypt/live/{{ _domain }}/fullchain.pem
        map                      Example *
      }
  notify: Restart lshttpd

# - name: Point the WebAdmin listener at the Let's Encrypt certificate
#   lineinfile:
#     path: "{{ ols_admin_conf }}"
#     regexp: '^\s*{{ item.key }}\s+.*$'
#     line: "  {{ item.key }}               /etc/letsencrypt/live/{{ _domain }}/{{ item.file }}"
#   loop:
#     - {key: 'keyFile', file: 'privkey.pem'}
#     - {key: 'certFile', file: 'fullchain.pem'}
#   notify: Restart lshttpd

- name: Update certs
  lineinfile:
    path: "{{ ols_admin_conf }}"
    line: "{{ item.line }}"
    search_string: "{{ item.cert }}"
  loop:
    - { line: "  keyFile \t\t   /etc/letsencrypt/live/{{ _domain }}/privkey.pem", cert: 'privkey.pem' }
    - { line: "  certFile \t\t   /etc/letsencrypt/live/{{ _domain }}/fullchain.pem", cert: 'certFile' }