---
- name: Configuring cpanel
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  vars_files: [group_vars/linode/vars]
  roles:
    - common
    - cpanel-ubuntu
    - post
