---
- name: Issue Let's Encrypt cert and configure HTTPS
  import_role:
    name: certbot_ssl

- name: Add host-mismatch redirect to HTTPS vhost
  blockinfile:
    path: /etc/apache2/sites-available/joomla-le-ssl.conf
    insertbefore: '^SSLCertificateFile'
    marker: "# {mark}"
    block: |
      RewriteCond %{HTTP_HOST} !={{ _domain }}
      RewriteRule ^ https://{{ _domain }}%{REQUEST_URI} [R=permanent,L]
  notify: Reload apache2
