---
- name: Install MariaDB
  import_tasks: mariadb.yml

- name: Install PHP
  import_tasks: php.yml

- name: Configure Apache
  import_tasks: apache.yml

- name: Install Joomla
  import_tasks: joomla.yml

- name: Post-install hardening
  import_tasks: post_install.yml

- name: Issue Let's Encrypt cert
  import_tasks: certbot.yml
