---
- name: Download Claude installer
  get_url:
    url: https://claude.ai/install.sh
    dest: /tmp/claude-install.sh
    mode: "0755"
  register: claude_installer

- name: Run Claude installer
  script: "{{ claude_installer.dest }}"
  register: claude_install
  changed_when: claude_install.rc == 0

- name: Update local PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    insertafter: EOF
    state: present

# cleanup
- name: Remove Claude installer
  file:
    path: "{{ claude_installer }}"
    state: absent
