---
- name: Restart vault
  ansible.builtin.systemd_service:
    name: vault
    state: restarted

- name: Reload vault
  ansible.builtin.systemd_service:
    name: vault
    state: reloaded

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
