---
- name: Install requested add-ons
  import_role:
    name: addons
  when:
    - add_ons != ['none']

- name: Copy MOTD template to /etc/motd
  template:
    src: motd.j2
    dest: /etc/motd
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Write credentials file
  copy:
    dest: "/home/{{ username }}/.credentials"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}

      MariaDB Root Password: {{ mysql_root_password }}
      Microweber DB Name: {{ mw_db_name }}
      Microweber DB User: {{ mw_db_user }}
      Microweber DB Password: {{ mw_db_password }}

      Microweber Admin Username: {{ mw_admin_username }}
      Microweber Admin Password: {{ mw_admin_password }}
      Microweber Admin Email: {{ admin_email }}
