---
- name: Install Docker latest
  import_role:
    name: docker

- name: Installing docker-compose
  apt:
    pkg: [docker-compose]
    state: present

- name: Ensure Saltcorn directory exists
  file:
    path: /opt/saltcorn
    state: directory
    mode: '0755'

- name: Template docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/saltcorn/docker-compose.yml
    mode: '0644'
