---
- name: Download NodeSource GPG key
  get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: '0644'

- name: Add NodeSource apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_24.x nodistro main"
    state: present
    filename: nodesource
    update_cache: true

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: true

- name: Create Saltcorn user
  user:
    name: saltcorn
    shell: /bin/bash
    create_home: true
    state: present
  become: true

- name: Install Saltcorn via npx
  command: npx saltcorn-install -y
  args:
    creates: /home/saltcorn/.local/bin/saltcorn
  become: true
  become_user: saltcorn

- name: Get UID of saltcorn user
  command: id -u saltcorn
  register: saltcorn_uid_result
  changed_when: false

- name: Ensure lingering is enabled for the saltcorn user
  command: loginctl enable-linger saltcorn
  changed_when: false

- name: Create systemd user directory if it does not exist
  file:
    path: /home/saltcorn/.config/systemd/user
    state: directory
    owner: saltcorn
    group: saltcorn
    mode: '0755'

- name: Write saltcorn systemd user service file
  template:
    src: saltcorn.service.j2
    dest: /home/saltcorn/.config/systemd/user/saltcorn.service
    owner: saltcorn
    group: saltcorn
    mode: '0644'

- name: Enable and restart saltcorn user service
  systemd:
    name: saltcorn
    enabled: true
    state: restarted
    daemon_reload: true
    scope: user
  become: true
  become_user: saltcorn

- name: Set XDG_RUNTIME_DIR in .bashrc for saltcorn user
  lineinfile:
    path: /home/saltcorn/.bashrc
    line: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'
    state: present
    create: true
    insertafter: EOF
    owner: saltcorn
    group: saltcorn
    mode: '0644'

- name: Create Saltcorn admin user
  command: "/home/saltcorn/.local/bin/saltcorn create-user -a -e {{ soa_email_address }} -p '{{ saltcorn_admin_password }}'"
  become: true
  become_user: saltcorn
