---
- name: Install docker
  import_role:
    name: docker

- name: Import nvidia tasks
  import_tasks: nvidia.yml

- name: Import docker tasks
  import_tasks: docker.yml

- name: Import nginx tasks
  import_tasks: nginx.yml
