---
# wazuh handlers
- name: Restart wazuh dashboard
  systemd:
    name: wazuh-dashboard
    state: restarted
    enabled: true

- name: Reload nginx service
  systemd:
    name: nginx
    state: reloaded
    enabled: true

- name: Stop nginx service
  systemd:
    name: nginx
    state: stopped
    enabled: false
