---
name: Development Workflow
on:
  workflow_dispatch:
  pull_request_target:
jobs:
  check-workflow-permissions-job:
    name: Check workflow permissions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      environment: ${{ steps.check-permissions.outputs.environment }}
    env:
      AUTHOR_NAME: ${{ github.event.pull_request.user.login || github.actor }}
      AUTHOR_ASSOCIATION: ${{ github.event.pull_request.author_association || 'COLLABORATOR' }}
      PR_NUMBER: ${{ github.event.pull_request.number || 'branch' }}
      BRANCH: ${{ github.head_ref || github.ref_name }}
      TARGET: ${{ github.event.pull_request.base.ref || 'main'}}
    steps:
      - name: Check author permissions
        id: check-permissions
        run: |
          if [[ "$AUTHOR_ASSOCIATION" =~ ^(COLLABORATOR|MEMBER|OWNER)$ ]]; then
            echo "environment=development_internal" >> $GITHUB_OUTPUT
          else
            echo "environment=development_external" >> $GITHUB_OUTPUT
          fi
      - name: Print permissions summary
        run: |
          echo "## Permissions Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Field | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| **Author name** | ${{ env.AUTHOR_NAME }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Author Association** | ${{ env.AUTHOR_ASSOCIATION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **PR** | ${{ env.PR_NUMBER }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Branch** | ${{ env.BRANCH }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Target** | ${{ env.TARGET }} |" >> $GITHUB_STEP_SUMMARY
  approve-workflow-job:
    name: Approve workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: ${{ needs.check-workflow-permissions-job.outputs.environment }}
    needs: check-workflow-permissions-job
    steps:
      - name: Print deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Deployment has been approved and started to \`${{ needs.check-workflow-permissions-job.outputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
  static-code-analysis-shellcheck:
    name: Static code analysis - shellcheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: approve-workflow-job
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run ShellCheck
        run: bash .github/scripts/static-code-shellcheck.sh
  static-code-analysis-yamllint:
    name: Static code analysis - yamllint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: approve-workflow-job
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run yamllint
        run: bash .github/scripts/static-code-yamllint.sh
  static-code-analysis-ansbible-lint:
    name: Static code analysis - ansible-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: approve-workflow-job
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run ansible-lint
        run: bash .github/scripts/static-code-ansible-lint.sh
  get-updated-apps:
    name: Getting list of updated apps
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - static-code-analysis-shellcheck
      - static-code-analysis-yamllint
      - static-code-analysis-ansbible-lint
    outputs:
      configs: ${{ steps.configs-matrix.outputs.configs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Find updated apps
        id: configs-matrix
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          TARGET: ${{ github.event.pull_request.base.ref || 'main'}}
        run: bash .github/scripts/get-updated-apps.sh
  setup-job:
    name: Setup data for deployment and testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: get-updated-apps
    if: needs.get-updated-apps.outputs.configs != '[]'
    env:
      LINODE_API_SECRET: ${{ secrets.LINODE_API_SECRET }}
      LINODE_DOMAIN: ${{ secrets.LINODE_DOMAIN }}
      LINODE_SUBDOMAIN: ${{ secrets.LINODE_SUBDOMAIN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check and clean up domain records
        run: bash .github/scripts/setup-domain-records-cleanup.sh
  deployment-job:
    name: App deployment and testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [get-updated-apps, setup-job]
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.get-updated-apps.outputs.configs) }}
      max-parallel: 10
    env:
      LINODE_API_SECRET: ${{ secrets.LINODE_API_SECRET }}
      LINODE_ROOT_PASS: ${{ secrets.LINODE_ROOT_PASS }}
      LINODE_DOMAIN: ${{ secrets.LINODE_DOMAIN }}
      LINODE_SUBDOMAIN: ${{ secrets.LINODE_SUBDOMAIN }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get Linode configuration for ${{ matrix.app }}
        run: bash deployment_scripts/${{ matrix.app }}/linode-config.sh
      - name: Provisioning Linode for ${{ matrix.app }}
        id: linode-provisioning
        env:
          APP_NAME: ${{ matrix.app }}
        run: bash .github/scripts/linode-provisioning.sh
      - name: Deploying ${{ matrix.app }}
        env:
          APP_NAME: ${{ matrix.app }}
          BRANCH: ${{ github.head_ref || github.ref_name }}
          GH_USER: ${{ github.event.pull_request.head.repo.owner.login || github.repository_owner }}
          LINODE_IPV4: ${{ steps.linode-provisioning.outputs.LINODE_IPV4 }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: bash .github/scripts/app-installation.sh
      - name: Deleting Linode for ${{ matrix.app }}
        if: always()
        env:
          LINODE_ID: ${{ steps.linode-provisioning.outputs.LINODE_ID }}
        run: bash .github/scripts/linode-deletion.sh
      - name: Deleting domain records for ${{ matrix.app }}
        if: always()
        env:
          LINODE_IPV4: ${{ steps.linode-provisioning.outputs.LINODE_IPV4 }}
        run: bash .github/scripts/teardown-domain-records-cleanup.sh
